# render.yaml
services:
  - type: web
    name: breath-easy-backend-fresh
    env: python
    region: frankfurt
    branch: main
    rootDirectory: backend
    buildCommand: pip install -r requirements_deployment.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PREFER_HF
        value: "true"
      - key: USE_HF
        value: "true"
      - key: WHISPER_MODEL_SIZE
        value: "tiny"
