# render.yaml
services:
  - type: web
    name: breath-easy-thesis-backend
    env: python
    region: frankfurt
    branch: main
    rootDirectory: backend
    buildCommand: pip install -r requirements_deployment.txt
    startCommand: uvicorn fastapi_app_improved:app --host 0.0.0.0 --port 10000
    autoDeploy: true
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PREFER_HF
        value: "true"
      - key: USE_HF
        value: "true"
      - key: WHISPER_MODEL_SIZE
        value: "tiny"
      - key: HF_TOKEN
        value: "your_hf_token_here"
