# render.yaml
services:
  - type: web
    name: breath-easy-thesis-backend
    env: python
    region: frankfurt
    branch: main
    rootDirectory: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn fastapi_app:app --host 0.0.0.0 --port 10000
    autoDeploy: true
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: MODEL_PATH
        value: "./model.pkl"
